import re
from pathlib import Path
root = Path(__file__).resolve().parents[2] / 'RMPStable/src/RemoveMultiplayerPlayerLimit/Features/LiveSharing'
source = (root / 'SpectatorSnapshot.cs').read_text(encoding='utf-8-sig')
parts = re.split(r'internal sealed class (\w+)\s*\{', source)
out = ['using System;', 'using System.Collections.Generic;', '', 'namespace RemoveMultiplayerPlayerLimit.Features.LiveSharing;', '', '// Generated by tests/LiveSharingSmoke/generate_equality.py from SpectatorSnapshot.cs.', '// Exact typed comparison: no serialization, reflection, or hash collisions.', 'internal static class SnapshotEquality', '{', '\tinternal static bool Array<T>(T[]? a, T[]? b)', '\t{', '\t\tif (ReferenceEquals(a, b)) return true;', '\t\tif (a == null || b == null || a.Length != b.Length) return false;', '\t\tfor (int i = 0; i < a.Length; i++) if (!EqualityComparer<T>.Default.Equals(a[i], b[i])) return false;', '\t\treturn true;', '\t}', '\tinternal static bool List<T>(List<T>? a, List<T>? b, Func<T, T, bool> equal)', '\t{', '\t\tif (ReferenceEquals(a, b)) return true;', '\t\tif (a == null || b == null || a.Count != b.Count) return false;', '\t\tfor (int i = 0; i < a.Count; i++) if (!equal(a[i], b[i])) return false;', '\t\treturn true;', '\t}', '\tinternal static bool Equal(string a, string b) => a == b;']
for i in range(1, len(parts), 2):
    cls, body = parts[i:i+2]
    props = re.findall(r'public ([\w<>\[\]?]+) (\w+) \{ get; set; \}', body)
    conditions = []
    for typ, prop in props:
        x, y = f'a.{prop}', f'b.{prop}'
        if '[]' in typ: expr = f'Array({x}, {y})'
        elif typ.startswith('List<'): expr = f'List({x}, {y}, Equal)'
        elif typ.rstrip('?').endswith(('Snapshot', 'Revisions')): expr = f'Equal({x}, {y})'
        else: expr = f'{x} == {y}'
        conditions.append(expr)
    out += [f'\tinternal static bool Equal({cls}? a, {cls}? b) => ReferenceEquals(a, b) ||', '\t\t(a != null && b != null &&']
    out += ['\t\t\t' + c + (' &&' if j < len(conditions)-1 else ');') for j, c in enumerate(conditions)]
    if cls == 'CardSnapshot':
        face = [c for c in conditions if 'a.Transform' not in c]
        out += ['\tinternal static bool SameCardFace(CardSnapshot a, CardSnapshot b) =>', '\t\t' + ' &&\n\t\t'.join(face) + ';']
out += ['}', '']
(root / 'SnapshotEquality.cs').write_text('\n'.join(out), encoding='utf-8')
