using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using Godot;
using HarmonyLib;
using MegaCrit.Sts2.Core.Entities.Multiplayer;
using MegaCrit.Sts2.Core.GameActions;
using MegaCrit.Sts2.Core.GameActions.Multiplayer;
using MegaCrit.Sts2.Core.Multiplayer;
using MegaCrit.Sts2.Core.Multiplayer.Game;
using MegaCrit.Sts2.Core.Multiplayer.Replay;
using MegaCrit.Sts2.Core.Nodes.Cards.Holders;
using MegaCrit.Sts2.Core.Nodes.Combat;
using MegaCrit.Sts2.Core.Entities.Creatures;
using MegaCrit.Sts2.Core.Nodes.Potions;
using MegaCrit.Sts2.Core.Nodes.Screens.Map;
using MegaCrit.Sts2.Core.Nodes.GodotExtensions;
using MegaCrit.Sts2.Core.Nodes.Screens.Shops;
using MegaCrit.Sts2.Core.Runs;
using MegaCrit.Sts2.Core.Rewards;

namespace RemoveMultiplayerPlayerLimit.Features.LiveSharing;

internal sealed class MirrorOperation
{
    public string Kind { get; set; } = "";
    public string NodeKey { get; set; } = "";
    public string Value { get; set; } = "";
    public byte[] Payload { get; set; } = Array.Empty<byte>();
}

// Record authoritative native decisions. The replica runs the original
// singleplayer room/UI logic, including its real choice tasks and rewards.
// Native hooks/resumes/enemy turns are generated by that logic, not duplicated.
internal static class MirrorJournal
{
    internal static CombatReplay? Checkpoint { get; private set; }
    internal static readonly List<MirrorOperation> Operations = new();
    internal static bool ReplicaActive;
    internal static readonly Queue<CardReward> ReplicaCardRewards = new();
    private static readonly Dictionary<CardReward, string> RewardOptions = new();
    internal static void ResetReplicaRewards() { ReplicaCardRewards.Clear(); RewardOptions.Clear(); }
    private static RunState? _checkpointState;
    private static int _checkpointAct = -1;
    private static CombatReplay? _primedRestore;
    internal static void PrimeRestore(MegaCrit.Sts2.Core.Saves.SerializableRun save)
    {
        _primedRestore = null;
        RunManager.Instance.CombatReplayWriter.RecordInitialState(save);
        _primedRestore = Checkpoint;
    }
    internal static void FinishRestore() => _primedRestore = null;
    internal static void EnsureCheckpoint(RunState state)
    {
        if (!MirrorRenderer.IsRenderer && state.CurrentRoom != null && (!ReferenceEquals(state, _checkpointState) ||
            state.CurrentRoom is MegaCrit.Sts2.Core.Rooms.MapRoom && state.CurrentActIndex != _checkpointAct))
            RunManager.Instance.CombatReplayWriter.RecordInitialState(RunManager.Instance.ToSave(null));
    }
    private static bool _installed;
    private static int _uiDepth;
    private const BindingFlags Any = BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.Static;
    private static bool Recording => !MirrorRenderer.IsRenderer && !LiveSharingController.SourceMenuOpen && RunManager.Instance.NetService?.Type == NetGameType.Singleplayer && Checkpoint != null;
    internal static void Initialize()
    {
        if (_installed) return;
        MirrorFastRestore.Initialize();
        var harmony = new Harmony("RMPStable.NativeMirrorJournal");
        void Patch(MethodBase method, string? prefix = null, string? postfix = null, string? finalizer = null) => harmony.Patch(method,
            prefix == null ? null : new HarmonyMethod(typeof(MirrorJournal).GetMethod(prefix, Any)),
            postfix == null ? null : new HarmonyMethod(typeof(MirrorJournal).GetMethod(postfix, Any)),
            finalizer: finalizer == null ? null : new HarmonyMethod(typeof(MirrorJournal).GetMethod(finalizer, Any)));
        Patch(typeof(CombatReplayWriter).GetMethod("RecordInitialState", Any)!, postfix: nameof(CheckpointRecorded));
        Patch(typeof(ActionQueueSet).GetMethod("EnqueueWithoutSynchronizing", Any)!, prefix: nameof(ActionQueued));
        Patch(typeof(NClickableControl).GetMethod("ForceClick", Any)!, nameof(ForcedButton), finalizer: nameof(EndUi));
        Patch(typeof(NClickableControl).GetMethod("OnReleaseHandler", Any)!, nameof(ReleasedButton), finalizer: nameof(EndUi));
        Patch(typeof(GodotObject).GetMethod("EmitSignal", new[] { typeof(StringName), typeof(Variant[]) })!, nameof(SignalEmitted), finalizer: nameof(EndUi));
        Patch(typeof(NMerchantSlot).GetMethod("OnSelected", Any)!, nameof(MerchantSelected), finalizer: nameof(EndUi));
        Patch(typeof(NetReplayGameService).GetProperty("Type")!.GetMethod!, postfix: nameof(ReplicaServiceType));
        Patch(typeof(NCardPlay).GetMethod("TryPlayCard", Any)!, prefix: nameof(ReplicaCardPlay));
        Patch(typeof(Viewport).GetMethod("GetMousePosition")!, postfix: nameof(ReplicaMousePosition));
        Patch(typeof(NTargetManager).GetMethod("FinishTargeting", Any)!, prefix: nameof(TargetFinished), finalizer: nameof(EndUi));
        Patch(typeof(NPotionHolder).GetMethod("UsePotion", Any)!, prefix: nameof(PotionUsed), finalizer: nameof(EndUi));
        Patch(typeof(NPotionPopup).GetMethod("Remove", Any)!, prefix: nameof(PopupRemoved), finalizer: nameof(EndUi));
        Patch(typeof(NMapScreen).GetMethod("ProcessScrollEvent", Any)!, prefix: nameof(ScrollInput));
        Patch(typeof(NScrollableContainer).GetMethod("ProcessScrollEvent", Any)!, prefix: nameof(ScrollInput));
        Patch(typeof(NMapDrawings).GetMethod("BeginLineLocal", Any)!, prefix: nameof(DrawingStarted));
        Patch(typeof(NMapDrawings).GetMethod("UpdateCurrentLinePositionLocal", Any)!, prefix: nameof(DrawingMoved));
        Patch(typeof(NMapDrawings).GetMethod("StopLineLocal", Any)!, prefix: nameof(DrawingStopped));
        Patch(typeof(NMapDrawings).GetMethod("SetDrawingModeLocal", Any)!, prefix: nameof(DrawingModeChanged));
        Patch(typeof(NMouseModeMapDrawingInput).GetMethod("_Input", Any)!, prefix: nameof(ReplicaDrawingInput));
        Patch(typeof(NMouseHeldMapDrawingInput).GetMethod("_Input", Any)!, prefix: nameof(ReplicaDrawingInput));
        Patch(typeof(NMapScreen).GetMethod("_GuiInput", Any)!, prefix: nameof(ReplicaDrawingInput));
        Patch(typeof(CardReward).GetMethod("Populate", Any)!, prefix: nameof(RewardPopulating), postfix: nameof(RewardPopulated));
        _installed = true;
    }
    private static void ReplicaServiceType(ref NetGameType __result)
    { if (MirrorRenderer.IsRenderer && ReplicaActive) __result = NetGameType.Singleplayer; }
    private static bool ReplicaCardPlay(NCardPlay __instance, Creature? target)
    {
        if (!MirrorRenderer.IsRenderer) return true;
        MirrorRenderer.Active?.SubmitNativeCard(__instance, target);
        return false;
    }
    private static void ReplicaMousePosition(Viewport __instance, ref Vector2 __result)
    {
        if (MirrorRenderer.IsRenderer && MirrorRenderer.Active is { } renderer && __instance == MegaCrit.Sts2.Core.Nodes.NGame.Instance?.GetViewport())
            __result = renderer.NativePointer;
    }
    private static void CheckpointRecorded()
    {
        if (MirrorRenderer.IsRenderer || RunManager.Instance.NetService?.Type != NetGameType.Singleplayer) return;
        var recorded = MirrorState.CurrentReplay;
        _checkpointState = RunManager.Instance.DebugOnlyGetState();
        _checkpointAct = _checkpointState?.CurrentActIndex ?? -1;
        // The saved checkpoint can rebuild in parallel with the source scene.
        // Keep its generation if room entry has not advanced any native anchor.
        // A hook that advances an anchor falls back to the later checkpoint.
        if (MirrorFastRestore.Source && _primedRestore is { } prime && recorded != null &&
            prime.nextActionId == recorded.nextActionId && prime.nextHookId == recorded.nextHookId && prime.nextChecksumId == recorded.nextChecksumId &&
            prime.choiceIds.SequenceEqual(recorded.choiceIds) && prime.rewardIds.SequenceEqual(recorded.rewardIds))
        { Checkpoint = prime; return; }
        Checkpoint = recorded;
        if (MirrorFastRestore.Source && _primedRestore != null && recorded != null)
        {
            Checkpoint = MirrorState.Unpack<CombatReplay>(MirrorState.Pack(recorded));
            Checkpoint.serializableRun.PreFinishedRoom = _primedRestore.serializableRun.PreFinishedRoom;
        }
        Operations.Clear(); RewardOptions.Clear();
        LiveSharingController.PublishRestoreCheckpoint();
    }
    private static void ActionQueued(GameAction gameAction)
    {
        if (!Recording || _uiDepth != 0 || gameAction is GenericHookGameAction or ReadyToBeginEnemyTurnAction or UsePotionAction or MoveToMapCoordAction or VoteForMapCoordAction or VoteToMoveToNextActAction) return;
        if (!gameAction.RecordableToReplay) return;
        var record = new CombatReplayEvent { eventType = CombatReplayEventType.GameAction, playerId = gameAction.OwnerId, action = gameAction.ToNetAction() };
        Operations.Add(new MirrorOperation { Kind = "game", Payload = MirrorState.Pack(record) });
    }
    private static void BeginUi(Node node, string kind, out bool entered)
    {
        entered = false;
        if (!Recording || _uiDepth != 0 || MirrorNativeUi.Key(node) is not { Length: > 0 } key) return;
        Operations.Add(new MirrorOperation { Kind = kind, NodeKey = key });
        _uiDepth++; entered = true;
    }
    private static void ForcedButton(NClickableControl __instance, out bool __state)
    {
        __state = false;
        if (__instance.IsEnabled && !MirrorNativeUi.IgnoreButton(__instance)) BeginUi(__instance, "button", out __state);
    }
    private static void ReleasedButton(NClickableControl __instance, out bool __state)
    {
        __state = false;
        if ((bool)typeof(NClickableControl).GetField("_isPressed", Any)!.GetValue(__instance)! && !MirrorNativeUi.IgnoreButton(__instance)) BeginUi(__instance, "button", out __state);
    }
    private static void SignalEmitted(GodotObject __instance, StringName signal, out bool __state)
    {
        __state = false;
        if (signal.ToString() == "Pressed" && __instance is NCardHolder holder && !MirrorNativeUi.IsHandPlay(holder) && MirrorNativeUi.Parent<NMerchantSlot>(holder) == null)
            BeginUi(holder, "card", out __state);
    }
    private static void MerchantSelected(NMerchantSlot __instance, out bool __state) => BeginUi(__instance, "buy", out __state);
    private static void PotionUsed(NPotionHolder __instance, out bool __state) => BeginUi(__instance, "potion", out __state);
    private static void PopupRemoved(NPotionPopup __instance, out bool __state) => BeginUi(__instance, "popupCancel", out __state);
    private static void TargetFinished(NTargetManager __instance, bool cancel, out bool __state)
    {
        __state = false;
        if (!Recording || !__instance.IsInSelection || NPlayerHand.Instance is { } hand && typeof(NPlayerHand).GetField("_currentCardPlay", Any)?.GetValue(hand) is NCardPlay play && GodotObject.IsInstanceValid(play) && !play.IsQueuedForDeletion()) return;
        var node = typeof(NTargetManager).GetProperty("HoveredNode", Any)!.GetValue(__instance) as Node;
        if (cancel) BeginUi(__instance, "cancelTarget", out __state);
        else if (node != null) BeginUi(node, "target", out __state);
    }
    private static void ScrollInput(Control __instance, InputEvent inputEvent)
    {
        if (!Recording || _uiDepth != 0) return;
        float amount = inputEvent is InputEventPanGesture pan ? pan.Delta.Y / .8f : inputEvent is InputEventMouseButton { Pressed: true } wheel ? wheel.ButtonIndex == MouseButton.WheelUp ? -1 : wheel.ButtonIndex == MouseButton.WheelDown ? 1 : 0 : 0;
        string key = MirrorNativeUi.Key(__instance);
        if (amount != 0 && key.Length > 0) Operations.Add(new MirrorOperation { Kind = "scroll", NodeKey = key,
            Value = (amount > 0 ? "down:" : "up:") + Math.Abs(amount).ToString(System.Globalization.CultureInfo.InvariantCulture) });
    }
    private static Exception? EndUi(Exception? __exception, bool __state)
    { if (__state) _uiDepth--; return __exception; }
    private static string Point(Vector2 position) => position.X.ToString(System.Globalization.CultureInfo.InvariantCulture) + "," + position.Y.ToString(System.Globalization.CultureInfo.InvariantCulture);
    private static void DrawingEvent(NMapDrawings node, string kind, string value)
    {
        if (Recording && _uiDepth == 0 && MirrorNativeUi.Key(node) is { Length: > 0 } key)
            Operations.Add(new MirrorOperation { Kind = kind, NodeKey = key, Value = value });
    }
    private static void DrawingStarted(NMapDrawings __instance, Vector2 position, DrawingMode? overrideDrawingMode) =>
        DrawingEvent(__instance, "drawStart", (int)(overrideDrawingMode ?? __instance.GetLocalDrawingMode(false)) + "," + Point(position));
    private static void DrawingMoved(NMapDrawings __instance, Vector2 position) => DrawingEvent(__instance, "drawMove", Point(position));
    private static void DrawingStopped(NMapDrawings __instance) => DrawingEvent(__instance, "drawEnd", "");
    private static void DrawingModeChanged(NMapDrawings __instance, DrawingMode drawingMode) => DrawingEvent(__instance, "drawMode", ((int)drawingMode).ToString());
    private static bool ReplicaDrawingInput() => !MirrorRenderer.IsRenderer;
    private static void RewardPopulating(CardReward __instance, out bool __state) => __state = !__instance.IsPopulated;
    private static void RewardPopulated(CardReward __instance, bool __state)
    {
        if (!__instance.IsPopulated) return;
        var payload = MirrorState.Pack(new MirrorCardBatch { Cards = __instance.Cards.Select(c => c.ToSerializable()).ToList() });
        var fingerprint = Convert.ToBase64String(payload);
        if (RewardOptions.TryGetValue(__instance, out var prior) && prior == fingerprint) return;
        RewardOptions[__instance] = fingerprint;
        if (MirrorRenderer.IsRenderer) { ReplicaCardRewards.Enqueue(__instance); return; }
        if (Recording) { Operations.Add(new MirrorOperation { Kind = "rewardCards", Payload = payload }); GD.Print("[RMP:Mirror:Rewards] authoritative options=" + string.Join(",", __instance.Cards.Select(c => c.Id))); }
    }
}
