using System;
using System.Collections.Generic;

namespace RemoveMultiplayerPlayerLimit.Features.LiveSharing;

// Generated by tests/LiveSharingSmoke/generate_equality.py from SpectatorSnapshot.cs.
// Exact typed comparison: no serialization, reflection, or hash collisions.
internal static class SnapshotEquality
{
	internal static bool Array<T>(T[]? a, T[]? b)
	{
		if (ReferenceEquals(a, b)) return true;
		if (a == null || b == null || a.Length != b.Length) return false;
		for (int i = 0; i < a.Length; i++) if (!EqualityComparer<T>.Default.Equals(a[i], b[i])) return false;
		return true;
	}
	internal static bool List<T>(List<T>? a, List<T>? b, Func<T, T, bool> equal)
	{
		if (ReferenceEquals(a, b)) return true;
		if (a == null || b == null || a.Count != b.Count) return false;
		for (int i = 0; i < a.Count; i++) if (!equal(a[i], b[i])) return false;
		return true;
	}
	internal static bool Equal(string a, string b) => a == b;
	internal static bool Equal(SpectatorSnapshot? a, SpectatorSnapshot? b) => ReferenceEquals(a, b) ||
		(a != null && b != null &&
			a.Schema == b.Schema &&
			Equal(a.Revisions, b.Revisions) &&
			a.Session == b.Session &&
			a.SourceId == b.SourceId &&
			List(a.Sources, b.Sources, Equal) &&
			Equal(a.Pointer, b.Pointer) &&
			Equal(a.Control, b.Control) &&
			a.Room == b.Room &&
			a.Page == b.Page &&
			a.Character == b.Character &&
			a.Summary == b.Summary &&
			a.Detail == b.Detail &&
			a.Width == b.Width &&
			a.Height == b.Height &&
			List(a.Background, b.Background, Equal) &&
			List(a.Creatures, b.Creatures, Equal) &&
			List(a.Cards, b.Cards, Equal) &&
			List(a.Deck, b.Deck, Equal) &&
			List(a.Items, b.Items, Equal) &&
			List(a.Inventory, b.Inventory, Equal) &&
			List(a.Choices, b.Choices, Equal) &&
			List(a.HudArt, b.HudArt, Equal) &&
			List(a.HudLabels, b.HudLabels, Equal) &&
			List(a.HudHovers, b.HudHovers, Equal) &&
			List(a.Relics, b.Relics, Equal) &&
			List(a.Piles, b.Piles, Equal) &&
			List(a.ModalArt, b.ModalArt, Equal) &&
			List(a.ModalLabels, b.ModalLabels, Equal) &&
			Array(a.DeckButtonRect, b.DeckButtonRect) &&
			List(a.UnderlayCards, b.UnderlayCards, Equal) &&
			List(a.UnderlayItems, b.UnderlayItems, Equal) &&
			List(a.RewardArt, b.RewardArt, Equal) &&
			List(a.RewardLabels, b.RewardLabels, Equal) &&
			List(a.PageArt, b.PageArt, Equal) &&
			List(a.PageLabels, b.PageLabels, Equal) &&
			List(a.Drawings, b.Drawings, Equal) &&
			List(a.Hovers, b.Hovers, Equal) &&
			a.UnderlayPage == b.UnderlayPage &&
			List(a.CombatHudArt, b.CombatHudArt, Equal) &&
			List(a.CombatHudLabels, b.CombatHudLabels, Equal) &&
			a.Culture == b.Culture);
	internal static bool Equal(PointerSnapshot? a, PointerSnapshot? b) => ReferenceEquals(a, b) ||
		(a != null && b != null &&
			a.Session == b.Session &&
			a.SourceId == b.SourceId &&
			a.Sequence == b.Sequence &&
			a.Visible == b.Visible &&
			a.X == b.X &&
			a.Y == b.Y &&
			a.Texture == b.Texture &&
			a.HotspotX == b.HotspotX &&
			a.HotspotY == b.HotspotY &&
			a.ScaleX == b.ScaleX &&
			a.ScaleY == b.ScaleY);
	internal static bool Equal(SpectatorRevisions? a, SpectatorRevisions? b) => ReferenceEquals(a, b) ||
		(a != null && b != null &&
			a.Hud == b.Hud &&
			a.Background == b.Background &&
			a.Creatures == b.Creatures &&
			a.Screen == b.Screen &&
			a.Inventory == b.Inventory &&
			a.Offers == b.Offers &&
			a.Cards == b.Cards &&
			a.Deck == b.Deck &&
			a.Sources == b.Sources);
	internal static bool Equal(ParticipantSnapshot? a, ParticipantSnapshot? b) => ReferenceEquals(a, b) ||
		(a != null && b != null &&
			a.Id == b.Id &&
			a.Name == b.Name &&
			a.Simulated == b.Simulated);
	internal static bool Equal(CardSnapshot? a, CardSnapshot? b) => ReferenceEquals(a, b) ||
		(a != null && b != null &&
			a.ControlId == b.ControlId &&
			a.ArtKey == b.ArtKey &&
			List(a.Art, b.Art, Equal) &&
			List(a.Labels, b.Labels, Equal) &&
			Array(a.Transform, b.Transform) &&
			a.Id == b.Id &&
			a.Title == b.Title &&
			a.Description == b.Description &&
			a.Type == b.Type &&
			a.Cost == b.Cost &&
			a.StarCost == b.StarCost &&
			a.Upgraded == b.Upgraded &&
			a.Ancient == b.Ancient &&
			a.Sold == b.Sold &&
			a.Price == b.Price &&
			a.Portrait == b.Portrait &&
			a.Frame == b.Frame &&
			a.Border == b.Border &&
			a.Banner == b.Banner &&
			a.EnergyIcon == b.EnergyIcon &&
			a.FrameMaterial == b.FrameMaterial &&
			a.BannerMaterial == b.BannerMaterial &&
			a.AncientBorder == b.AncientBorder &&
			a.AncientText == b.AncientText &&
			a.EnchantmentIcon == b.EnchantmentIcon &&
			a.EnchantmentAmount == b.EnchantmentAmount &&
			a.SortCost == b.SortCost &&
			a.SortType == b.SortType &&
			Array(a.CostColor, b.CostColor) &&
			Array(a.CostOutline, b.CostOutline) &&
			Array(a.StarColor, b.StarColor) &&
			Array(a.StarOutline, b.StarOutline) &&
			List(a.Tips, b.Tips, Equal) &&
			Equal(a.Upgrade, b.Upgrade) &&
			Equal(a.Base, b.Base));
	internal static bool SameCardFace(CardSnapshot a, CardSnapshot b) =>
		a.ControlId == b.ControlId &&
		a.ArtKey == b.ArtKey &&
		List(a.Art, b.Art, Equal) &&
		List(a.Labels, b.Labels, Equal) &&
		a.Id == b.Id &&
		a.Title == b.Title &&
		a.Description == b.Description &&
		a.Type == b.Type &&
		a.Cost == b.Cost &&
		a.StarCost == b.StarCost &&
		a.Upgraded == b.Upgraded &&
		a.Ancient == b.Ancient &&
		a.Sold == b.Sold &&
		a.Price == b.Price &&
		a.Portrait == b.Portrait &&
		a.Frame == b.Frame &&
		a.Border == b.Border &&
		a.Banner == b.Banner &&
		a.EnergyIcon == b.EnergyIcon &&
		a.FrameMaterial == b.FrameMaterial &&
		a.BannerMaterial == b.BannerMaterial &&
		a.AncientBorder == b.AncientBorder &&
		a.AncientText == b.AncientText &&
		a.EnchantmentIcon == b.EnchantmentIcon &&
		a.EnchantmentAmount == b.EnchantmentAmount &&
		a.SortCost == b.SortCost &&
		a.SortType == b.SortType &&
		Array(a.CostColor, b.CostColor) &&
		Array(a.CostOutline, b.CostOutline) &&
		Array(a.StarColor, b.StarColor) &&
		Array(a.StarOutline, b.StarOutline) &&
		List(a.Tips, b.Tips, Equal) &&
		Equal(a.Upgrade, b.Upgrade) &&
		Equal(a.Base, b.Base);
	internal static bool Equal(ControlSnapshot? a, ControlSnapshot? b) => ReferenceEquals(a, b) ||
		(a != null && b != null &&
			a.Context == b.Context &&
			List(a.Actions, b.Actions, Equal) &&
			List(a.Targets, b.Targets, Equal));
	internal static bool Equal(ControlActionSnapshot? a, ControlActionSnapshot? b) => ReferenceEquals(a, b) ||
		(a != null && b != null &&
			a.Id == b.Id &&
			a.Kind == b.Kind &&
			a.CardId == b.CardId &&
			a.Label == b.Label &&
			a.Enabled == b.Enabled &&
			a.RequiresTarget == b.RequiresTarget &&
			Array(a.Rect, b.Rect) &&
			List(a.TargetIds, b.TargetIds, Equal));
	internal static bool Equal(ControlTargetSnapshot? a, ControlTargetSnapshot? b) => ReferenceEquals(a, b) ||
		(a != null && b != null &&
			a.Id == b.Id &&
			Array(a.Rect, b.Rect));
	internal static bool Equal(ItemSnapshot? a, ItemSnapshot? b) => ReferenceEquals(a, b) ||
		(a != null && b != null &&
			List(a.Art, b.Art, Equal) &&
			List(a.Labels, b.Labels, Equal) &&
			Array(a.Rect, b.Rect) &&
			a.Name == b.Name &&
			a.Icon == b.Icon &&
			a.Text == b.Text &&
			a.Price == b.Price &&
			a.Sold == b.Sold);
	internal static bool Equal(CreatureSnapshot? a, CreatureSnapshot? b) => ReferenceEquals(a, b) ||
		(a != null && b != null &&
			a.EntityKey == b.EntityKey &&
			List(a.StateArt, b.StateArt, Equal) &&
			List(a.StateLabels, b.StateLabels, Equal) &&
			Array(a.Transform, b.Transform) &&
			Array(a.HealthRect, b.HealthRect) &&
			Array(a.IntentRect, b.IntentRect) &&
			a.Name == b.Name &&
			a.VisualScene == b.VisualScene &&
			a.Animation == b.Animation &&
			a.Player == b.Player &&
			a.Hp == b.Hp &&
			a.MaxHp == b.MaxHp &&
			a.Block == b.Block &&
			List(a.Powers, b.Powers, Equal) &&
			List(a.Intents, b.Intents, Equal));
	internal static bool Equal(TextSnapshot? a, TextSnapshot? b) => ReferenceEquals(a, b) ||
		(a != null && b != null &&
			a.ArtKey == b.ArtKey &&
			Array(a.LocalColor, b.LocalColor) &&
			a.Rich == b.Rich &&
			a.Text == b.Text &&
			a.Font == b.Font &&
			Array(a.Transform, b.Transform) &&
			Array(a.Size, b.Size) &&
			Array(a.Color, b.Color) &&
			Array(a.OutlineColor, b.OutlineColor) &&
			a.FontSize == b.FontSize &&
			a.OutlineSize == b.OutlineSize &&
			a.Alignment == b.Alignment &&
			a.VerticalAlignment == b.VerticalAlignment &&
			a.WrapMode == b.WrapMode);
	internal static bool Equal(ArtSnapshot? a, ArtSnapshot? b) => ReferenceEquals(a, b) ||
		(a != null && b != null &&
			a.Key == b.Key &&
			a.Parent == b.Parent &&
			a.Group == b.Group &&
			a.ClipChildren == b.ClipChildren &&
			a.ClipContents == b.ClipContents &&
			a.ZRelative == b.ZRelative &&
			a.BehindParent == b.BehindParent &&
			Array(a.Points, b.Points) &&
			a.Polygon == b.Polygon &&
			a.LineWidth == b.LineWidth &&
			a.BeginCap == b.BeginCap &&
			a.EndCap == b.EndCap &&
			a.Joint == b.Joint &&
			a.Antialiased == b.Antialiased &&
			a.Solid == b.Solid &&
			a.Skeleton == b.Skeleton &&
			a.Animation == b.Animation &&
			a.Texture == b.Texture &&
			a.Material == b.Material &&
			a.Shader == b.Shader &&
			List(a.ShaderValues, b.ShaderValues, Equal) &&
			Array(a.Transform, b.Transform) &&
			Array(a.Rect, b.Rect) &&
			Array(a.Tint, b.Tint) &&
			Array(a.SelfTint, b.SelfTint) &&
			a.Z == b.Z &&
			a.FlipH == b.FlipH &&
			a.FlipV == b.FlipV &&
			a.Stretch == b.Stretch &&
			Array(a.Region, b.Region) &&
			Array(a.PatchMargins, b.PatchMargins));
	internal static bool Equal(TipSnapshot? a, TipSnapshot? b) => ReferenceEquals(a, b) ||
		(a != null && b != null &&
			a.Title == b.Title &&
			a.Description == b.Description &&
			a.Icon == b.Icon &&
			a.Debuff == b.Debuff &&
			Equal(a.Card, b.Card));
	internal static bool Equal(DrawingSnapshot? a, DrawingSnapshot? b) => ReferenceEquals(a, b) ||
		(a != null && b != null &&
			Array(a.Transform, b.Transform) &&
			Array(a.Size, b.Size) &&
			Array(a.ViewportSize, b.ViewportSize) &&
			List(a.Lines, b.Lines, Equal));
	internal static bool Equal(ShaderValueSnapshot? a, ShaderValueSnapshot? b) => ReferenceEquals(a, b) ||
		(a != null && b != null &&
			a.Name == b.Name &&
			a.Kind == b.Kind &&
			Array(a.Values, b.Values) &&
			a.Texture == b.Texture);
	internal static bool Equal(HoverSnapshot? a, HoverSnapshot? b) => ReferenceEquals(a, b) ||
		(a != null && b != null &&
			Array(a.Rect, b.Rect) &&
			List(a.Tips, b.Tips, Equal));
	internal static bool Equal(PileSnapshot? a, PileSnapshot? b) => ReferenceEquals(a, b) ||
		(a != null && b != null &&
			a.Kind == b.Kind &&
			Array(a.Rect, b.Rect) &&
			List(a.Cards, b.Cards, Equal));
	internal static bool Equal(RelicSnapshot? a, RelicSnapshot? b) => ReferenceEquals(a, b) ||
		(a != null && b != null &&
			a.Title == b.Title &&
			a.Description == b.Description &&
			a.Flavor == b.Flavor &&
			a.Icon == b.Icon &&
			a.Rarity == b.Rarity &&
			Array(a.FrameHsv, b.FrameHsv) &&
			Array(a.RarityColor, b.RarityColor) &&
			Array(a.Rect, b.Rect) &&
			List(a.Tips, b.Tips, Equal) &&
			List(a.ExtraTips, b.ExtraTips, Equal));
}
